repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  #-   repo: https://github.com/asottile/reorder_python_imports
  #    rev: v3.0.1
  #    hooks:
  #    -   id: reorder-python-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'
    hooks:
      - id: poetry-check
      #      - id: poetry-lock
      - id: poetry-export
        args: [ "-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes" ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [ --skip, "B101", --recursive, clumper ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml
        args: [ "-i", "39642", "-i", "50916", "-i", "48542", "-i", "53071", "-i", "53125", "-i", "51668" ]
  - repo: https://github.com/dhatim/python-license-check
    rev: 0.9.1
    hooks:
      - id: liccheck
        language: system
  - repo: https://github.com/rtts/djhtml
    rev: '3.0.6'  # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
