# Generated by Django 4.0.2 on 2022-02-07 18:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="product",
            name="model",
        ),
    ]
