# Generated by Django 3.2.15 on 2022-09-16 03:24
import hashid_field.field
from django.db import migrations
from django.db import models

import web.models.news


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_sponsor"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline", models.CharField(max_length=100)),
                ("summary", models.TextField(blank=True, null=True)),
                ("contact", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to=web.models.news.get_file_path
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
