# Generated by Django 3.2.17 on 2023-02-13 22:03
import hashid_field.field
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_auto_20220916_0326"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=120)),
                ("message", models.TextField()),
            ],
        ),
    ]
