# Generated by Django 3.2.20 on 2023-08-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_auto_20230817_2010"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="_ical_cache",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="_ical_cache_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
