# Generated by Django 3.2.20 on 2023-08-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_auto_20230817_2023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="_ical_cache",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
